name = "alfa"
uuid = "d762b40b-22be-4ced-aa28-a3ac0c9c0493"
authors = ["Nils Kintscher"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
